---
- name: Enable Epel
  yum: name={{ epel_url}} state=present

- name: Install Redis
  yum: name={{ item }} state=installed
  with_items:
   - redis

- name: Start redis Service
  service: name=redis state=started enabled=true
