---
- name: Install Nginx repo
  yum: name={{ nginx_repo }} state=installed

- name: Install Nginx
  yum: name={{ item }} state=latest
  with_items:
   - nginx
   - python-passlib

- name: Disable default Vhost
  file: path=/etc/nginx/conf.d/{{ item }} state=absent
  with_items:
   - default.conf
   - example_ssl.conf
  notify:
   - restart nginx

- name: Enable Vhost
  template: src=vhost-nginx.j2 dest=/etc/nginx/conf.d/{{ domain }}.conf owner=root group=root mode=0644
  notify:
   - restart nginx

- name: Create htpasswd User
  htpasswd: path={{ nginx_confd }}/{{ domain }}.htpasswd name={{ username }} password={{ htpass }} owner=root group=root mode=0644
  notify:
   - restart nginx

- name: Start nginx Service
  service: name=nginx state=started enabled=true
