---
- name: Add Elasticsearch repo key
  rpm_key: key="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Enable Elasticsearch repository
  template: src=elasticsearch_repo.j2 dest=/etc/yum.repos.d/elasticsearch.repo

- name: Install Elasticsearch from repository
  yum: name={{ item }} state=latest
  with_items:
   - elasticsearch

- name: Elasticsearch configuration
  template: src=elasticsearch.yml.j2 dest={{ elastic_conf }} owner=root group=root mode=0644
  notify:
   - restart elasticsearch

- name: Start Elasticsearch Service
  service: name=elasticsearch state=started enabled=true
  
